version: '3'
services:
  #DATABASE
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=codechallengedb
    restart: unless-stopped

  # BACK-END
  back-end:
    image: coding-challenge-backend_springbootapp
    container_name: springbootapp
    ports:
      - 8080:8080
    restart: unless-stopped

  # FRONT-END
  angular-service:
    container_name: angular-front
    build: .
    volumes:
      - '.:/app'
    ports:
      - 4200:4200
    restart: unless-stopped
